

/*resource "local_file" "pet" {
    filename = var.filename
    content = var.content
    file_permission = var.permission
}

resource "local_file" "pet" {
    filename = var.filename
    content = "Pet  Mr.Horse"

    depends_on = [
        random_pet.my_pet
    ]
}*/

resource "local_file" "pet" {
    filename = var.filename
    content = "Pet  ${random_pet.my_pet.id}"
}


resource "random_pet" "my_pet" {
    prefix = var.prefix
    separator = var.separator
    length = var.length
}

output content {
    value = local_file.pet.content
    description = "Record the value of the pet id generated by the local_file resource"
}


output pet_name {
    value = random_pet.my_pet.id
    description = "Record the value of the pet id generated by the random_pet resource"
}


