/*variable "file-content" {
  type = map(any)
  default = {
    "statement1" = "Terraform is by Hashicorp"
    "Statement2" = "Terraform is Part of Devops"
  }
}

variable "book" {
  type = map(string)
  default = {
    "color" = "Yellow"
    "name"  = "Do it today"
  }
}

variable "book1" {
  type = map(number)
  default = {
    "Fiction" = "2"
    "Novels"  = "4"
    "Kids"    = "1"
  }
}

variable "motivational_book" {
  type = object({
    name           = string
    color          = string
    publised_on    = number
    chapters       = list(string)
    read_completed = bool
  })

  default = {
    name           = "Atomic_habits"
    color          = "white"
    publised_on    = 2018
    chapters       = ["one", "two", "three"]
    read_completed = true
  }

}

variable "book" {
  type    = tuple([string, number, bool])
  default = ["white", 2018, true]
}


variable "prefix" {

}
variable "separator" {

}
variable "length" {

}


variable "color" {

}


variable "publised_on" {

}*/

variable "filename" {
  default = "/home/remote_user/terraform-local-file/Map/pets.txt"
}
variable "content" {
  default = "This is a different pet file"
}


output content {
    value = random_pet.my_pet.id
    description = "Record the value of the pet id generated by the random_pet resource"
}


output pet_name {
    value = random_pet.my_pet.id
    description = "Record the value of the pet id generated by the random_pet resource"
}
